### PR TITLE
STYLE: Add an ITK KW Style overwrite file.

### PR DESCRIPTION
**Pull request by jhlegarreta**
Add a `ITKKWStyleOverwriteFile.txt` file to override the KW Style and
pass/skip the style check.

### CODE REVIEW

**Comment by jhlegarreta** [comment]
Note that I assumed that the **ITK** prefix has to exist in the filename. Please correct me if I'm wrong. 

Not sure why CI is failing in this case.

**Review by thewtex — CHANGES_REQUESTED** [review]
To override the header check, the rule to ignore the license header need to be added to the file.

Something linke

```
test2.h Header Disable
```

as documented here:

https://kitware.github.io/KWStyle/resources/documentation.html


We also need to rebase on `master` for the CircleCI configuration.

**Comment by jhlegarreta** [comment]
Done in 702d393. Sorry, thought that when finding an empty file it would just override the default ITK KW style and basically apply none of its rules.

**Review by thewtex — APPROVED** [review]
Well done! :green_apple:

**Pull request merged**
